---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "streams-stock-stats"
  namespace: "default"
  labels:
    app: "streams-stock-stats"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "streams-stock-stats"
  template:
    metadata:
      labels:
        app: "streams-stock-stats"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "streams-stock-stats"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: "kafka-streams-stockstat"
        image: "gcr.io/gwen-test-202722/kafka-streams-stockstat:latest"
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -DLOGLEVEL=INFO

