apiVersion: v1
kind: Service
metadata:
  name: streams-stock-stats
  labels:
    app: streams-stock-stats
spec:
  clusterIP: None
  selector:
    app: streams-stock-stats
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: streams-stock-stats
spec:
  serviceName: "streams-stock-stats"
  replicas: 2
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: streams-stock-stats
  template:
    metadata:
      labels:
        app: streams-stock-stats
    spec:
      containers:
      - name: kafka-streams-stockstat
        image: gcr.io/gwen-test-202722/kafka-streams-stockstat:latest
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -DLOGLEVEL=INFO
        volumeMounts:
        - name: rocksdb
          mountPath: /var/lib/kafka-streams
  volumeClaimTemplates:
  - metadata:
      name: rocksdb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
